---
title: "BSMM-lab-1"
subtitle: "BSMM 8740 Fall 2023"
author: "Jay Patki"
date: "18/09/2023"
format: html
editor: visual
self-contained: true
---

## Setup

Load packages and data:

```{r load-pkg-data}
#| message: false
# install the package 'Lahman'
install.packages('Lahman')
# load the package
library(Lahman)
```

```{r}
install.packages("tidyverse")
library(tidyverse)
```

## Exercises

### Exercise 1

```{r glimpse-data}
dplyr::glimpse(Teams)
```

The `Teams` dataset has 3015 observations and 48 variables.

### Exercise 2

...

```{r}
mets <- Teams  |>
  dplyr::filter(teamID == "NYN")
my_mets <- mets |> 
  dplyr::filter(yearID %in% 2004:2012)
my_mets |> 
  dplyr::select(yearID,G,W,L)
```

### Exercise 3

```{r}
mets_ben <- Teams |>
  dplyr::select(yearID, G, teamID,R, RA, W, L) |>
  dplyr::filter(teamID == "NYN" & yearID %in% 2004:2012)
mets_ben
```

```{r}
mets_ben <- mets_ben |>
  dplyr::rename(RS= R)    # new name = old name
mets_ben
```

### Exercise 4

```{r}
mets_ben <- mets_ben |>
  dplyr::mutate(WPct = 1 / (1 + (RA / RS) * 2))
mets_ben <- mets_ben |>
  dplyr::mutate(W_hat =WPct*G)
mets_ben
```

### Exercise 5

```{r}
mets_ben <- mets_ben |>
 dplyr:: mutate(Performance = ifelse(W > W_hat, "Better", "Worse"))
mets_ben
```

### Exercise 6

...

### Exercise 7

...

### Exercise 8

...

### Exercise 9

...

### Exercise 10

...
